<a href="https://colab.research.google.com/github/Hatoo22/2026-GP1-14/blob/main/modernbert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification using **ModernBERT**

In this project, we build a model to classify text comments into multiple toxicity categories (multi-label classification), such as:
- Bullying
- Threats
- Hate speech
- Sexual harassment

- other toxicity

We use Natural Language Processing (NLP) techniques to process text and train a deep learning model to detect toxic patterns.

###**Model: ModernBERT**

In this project, we used the **ModernBERT-large** model, which is an advanced version of BERT.  
It is designed to better understand language context, making it highly effective for NLP tasks like toxicity classification.

It is based on the Transformer architecture and provides deep contextual representations of text, which helps it:
- Understand the full meaning of sentences
- Distinguish between different types of toxicity
- Handle complex and long text inputs

# **Install Required Libraries**

In this step, we install and update the required libraries for the project.  
These libraries include tools for data processing, machine learning, and AI models such as transformers.  
If the libraries are already installed, you will see "already satisfied".

In [ ]:
!pip install -U "transformers>=4.48.0" datasets scikit-learn openpyxl accelerate

Requirement already satisfied: transformers>=4.48.0 in /usr/local/lib/python3.12/dist-packages (5.5.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.8.0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.48.0) (1.4.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.48.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.48.0) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.48.0) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.48.0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.48.0) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers>=4.48.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers>=4.48.0) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers>=4.48.0) (0.1.2)

#Import Libraries and Setup

This section imports all required libraries for building a multi-label classification model using deep learning.  
It includes tools for data processing, dataset splitting, evaluation metrics, and pretrained models from Hugging Face.

We also define key configurations such as:
- Model name
- Data file path
- Column names (text and labels)
- Training parameters like batch size and number of epochs

In [ ]:
import os
import random
import warnings
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
)

warnings.filterwarnings("ignore")

# ========= settings =========
MODEL_NAME = "answerdotai/ModernBERT-large"
FILE_PATH = "final_data_for_processing.xlsx"
TEXT_COL = "comment_text"
LABEL_COLS = [
    "is_toxic",
    "threat",
    "bullying",
    "sexual_harassment",
    "hate_speech",
    "other_toxicity"
]

OUTPUT_DIR = "./modernbert_multilabel_output"
MAX_LENGTH = 512
TRAIN_BATCH_SIZE = 2      # ModernBERT-large
EVAL_BATCH_SIZE = 2
GRAD_ACCUM = 8            # batch size
MAX_LENGTH = 512
LEARNING_RATE = 2e-5      #Learning rate
NUM_EPOCHS = 3          # Number of training epochs
WEIGHT_DECAY = 0.01
SEED = 42
THRESHOLD = 0.5           # threshold

# Set Random Seed

This section sets a fixed random seed to ensure reproducibility of results.  
This is very important in machine learning experiments so that results remain consistent across runs.

The seed is applied to:
- random
- numpy
- torch (GPU)


The data is shuffled randomly before training to prevent the model from learning any order-based patterns.
This is considered a **preprocessing step** because it prepares the data for better training.

In [ ]:
# Function to set random seed across all libraries

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)

# Load and Explore Data

In [ ]:
df = pd.read_excel(FILE_PATH)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.head()

Shape: (11222, 7)
Columns: ['comment', 'is_toxic', 'threat', 'bullying', 'sexual_harassment', 'hate_speech', 'other_toxicity']

,comment,is_toxic,threat,bullying,sexual_harassment,hate_speech,other_toxicity
0,"Massively underrated, massively difficult, mas...",0,0,0,0,0,0
1,This game is not so bad as people say. Of cour...,0,0,0,0,0,0
2,"Honestly, PUBG gets ugly fast. In ranked, solo...",1,0,1,0,0,1
3,"Great solo exploration game, I play this game ...",0,0,0,0,0,0
4,boring as hell you get about mins gameplay the...,0,0,0,0,0,0

# Split Dataset

This section splits the dataset into three parts:
- Training set
- Validation set
- Test set

First, the data is split into:
- 80% training
- 20% temporary (validation + test)

Then, the temporary set is split into:
- 10% validation
- 10% test

This helps to:
- Train the model effectively
- Evaluate performance during training
- Test the model on unseen data

In [ ]:
# Split data into training (80%) and temporary set (20%)
train_df, temp_df = train_test_split(
    df,
    test_size=0.2,
    random_state=SEED,
    shuffle=True
)
# Split temporary set into validation (10%) and test (10%)
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    random_state=SEED,
    shuffle=True
)

print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

Train: (8977, 7)
Validation: (1122, 7)
Test: (1123, 7)

**We prepare the data** for use with Hugging Face by selecting the text column and label columns,  
then converting the pandas DataFrame into a Dataset format.

This step is important because it:
- Makes the data compatible with the Trainer
- Simplifies tokenization and further processing

In [ ]:
TEXT_COL = "comment"
LABEL_COLS = [
    "is_toxic",
    "threat",
    "bullying",
    "sexual_harassment",
    "hate_speech",
    "other_toxicity"
]

def make_hf_dataset(dataframe):
    return Dataset.from_pandas(
        dataframe[[TEXT_COL] + LABEL_COLS].reset_index(drop=True)
    )

train_ds = make_hf_dataset(train_df)
val_ds = make_hf_dataset(val_df)
test_ds = make_hf_dataset(test_df)

# Tokenizer / Load Tokenizer

This section loads the tokenizer for the selected pretrained model.  


We use the same model name to ensure compatibility between:
- tokenizer
- model

The parameter use_fast=True enables the fast version for better performance.

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

# Tokens / Tokenization and Encoding

This section converts text data into numerical tokens using the tokenizer.  
It also prepares the multi-label targets for each example.

The process includes:
- Converting all text inputs to strings to avoid errors
- Tokenizing the text
- Setting maximum sequence length
- Creating label arrays for each sample

Then, this process is applied to:
- Training data
- Validation data
- Test data


Text is converted into numerical tokens so the model can understand it.
This is a key **preprocessing step** because it transforms text into a format suitable for the model.


Long texts are truncated to fit within the model’s maximum input length.
This is a **preprocessing step** because it ensures the data fits the model’s limitations.

In [ ]:
# Function to tokenize text and prepare labels
def tokenize_function(examples):
    # Ensure all text inputs are strings
    texts_to_tokenize = [str(text) for text in examples[TEXT_COL]]
        # Tokenize the text
    tokenized = tokenizer(
        texts_to_tokenize,
        truncation=True,
        max_length=MAX_LENGTH,
        padding=False
    )
    tokenized["labels"] = [
        [float(examples[col][i]) for col in LABEL_COLS]
        for i in range(len(examples[TEXT_COL]))
    ]
    return tokenized

train_tokenized = train_ds.map(tokenize_function, batched=True, remove_columns=train_ds.column_names)
val_tokenized = val_ds.map(tokenize_function, batched=True, remove_columns=val_ds.column_names)
test_tokenized = test_ds.map(tokenize_function, batched=True, remove_columns=test_ds.column_names)

Map:   0%|          | 0/8977 [00:00<?, ? examples/s]

Map:   0%|          | 0/1122 [00:00<?, ? examples/s]

Map:   0%|          | 0/1123 [00:00<?, ? examples/s]

In [ ]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# **Load Model**

This section loads a pretrained classification model from Hugging Face.  
We use ModernBERT-large, which is suitable for NLP tasks.

In [ ]:
# Load pretrained sequence classification model
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(LABEL_COLS),
    problem_type="multi_label_classification"
)

model.safetensors:   0%|          | 0.00/1.58G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/172 [00:00<?, ?it/s]

ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-large
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

# Compute Evaluation Metrics

This section computes evaluation metrics for the model in a multi-label classification setting.

In [ ]:
# Function to compute evaluation metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred

    # Handle invalid numerical values
    logits = np.nan_to_num(logits, nan=0.0, posinf=20.0, neginf=-20.0)
    # Convert logits to probabilities using Sigmoid
    probs = 1.0 / (1.0 + np.exp(-logits))
        # Apply threshold to get binary predictions
    preds = (probs >= THRESHOLD).astype(int)
        # Convert labels to integers
    labels = labels.astype(int)

    # Compute evaluation metrics
    metrics = {
        "micro_f1": f1_score(labels, preds, average="micro", zero_division=0),
        "macro_f1": f1_score(labels, preds, average="macro", zero_division=0),
        "weighted_f1": f1_score(labels, preds, average="weighted", zero_division=0),
        "micro_precision": precision_score(labels, preds, average="micro", zero_division=0),
        "micro_recall": recall_score(labels, preds, average="micro", zero_division=0),
        "subset_accuracy": accuracy_score(labels, preds),
    }
    return metrics

# Training Configuration

This section defines all training configurations using TrainingArguments.

In [ ]:
# Define training arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="steps",
    logging_steps=50,

    learning_rate=LEARNING_RATE,
    per_device_train_batch_size=TRAIN_BATCH_SIZE,
    per_device_eval_batch_size=EVAL_BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUM,

    num_train_epochs=NUM_EPOCHS,
    weight_decay=WEIGHT_DECAY,
    warmup_ratio=0.1,

    load_best_model_at_end=True,
    metric_for_best_model="micro_f1",
    greater_is_better=True,
    save_total_limit=2,
    # Precision settings
    report_to="none",
    fp16=False,
    bf16=False,
    seed=SEED,
    dataloader_num_workers=2
)

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

This section initializes the Trainer, which manages the full training and evaluation process.

We connect all components:
- The model
- Training and validation datasets
- Training configurations
- Metrics function

We also add Early Stopping to stop training if performance does not improve,  
which helps to:
- Reduce overfitting
- Save time and resources

In [ ]:
# Initialize Trainer
trainer = Trainer(
    model=model,      # Model
    args=training_args,        # Training arguments
    train_dataset=train_tokenized,       # Training dataset
    eval_dataset=val_tokenized,      # Validation dataset
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

# **Start Training**

This section starts the model training process using the Trainer.

The model will:
- Learn from the training data
- Evaluate on validation data after each epoch
- Automatically save the best model

The training output includes:
- Loss values
- Training steps
- Performance details

In [ ]:
train_result = trainer.train()
train_result

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1686, training_loss=0.6067062484836239, metrics={'train_runtime': 3201.8778, 'train_samples_per_second': 8.411, 'train_steps_per_second': 0.527, 'total_flos': 5884255954721844.0, 'train_loss': 0.6067062484836239, 'epoch': 3.0})

# Validate Model Performance

This section evaluates the model on the validation dataset separately.

We create a new Trainer for evaluation to:
- Generate predictions
- Compute metrics
- Analyze model performance

Finally, we print evaluation results such as:
- F1 Score
- Precision
- Recall
- Accuracy

In [ ]:
# Create a Trainer for evaluation only
from transformers import Trainer

val_trainer = Trainer(
    model=trainer.model,
    args=training_args,
    eval_dataset=val_tokenized,
    compute_metrics=compute_metrics,
    data_collator=data_collator,
    processing_class=tokenizer
)

val_output = val_trainer.predict(val_tokenized)   # Generate predictions and metrics

# Print validation results
print("Validation Results:")
print(val_output.metrics)

Validation Results:
{'test_loss': 0.04987103492021561, 'test_model_preparation_time': 0.0136, 'test_micro_f1': 0.9688493324856962, 'test_macro_f1': 0.9652229277278562, 'test_weighted_f1': 0.9685315777311259, 'test_micro_precision': 0.9934810951760105, 'test_micro_recall': 0.9454094292803971, 'test_subset_accuracy': 0.9367201426024956, 'test_runtime': 74.0942, 'test_samples_per_second': 15.143, 'test_steps_per_second': 7.571}

# Final Test Evaluation

This section performs the final evaluation on the test dataset,  
which was not used during training or validation.

This provides a realistic estimate of model performance.

We:
- Use the trained model
- Generate predictions on test data
- Compute and display evaluation metrics

In [ ]:
from transformers import Trainer
# Create a Trainer for test evaluation
test_trainer = Trainer(
    model=trainer.model,
    args=training_args,
    eval_dataset=test_tokenized,
    compute_metrics=compute_metrics,
    data_collator=data_collator,
    processing_class=tokenizer
)

test_output = test_trainer.predict(test_tokenized)   # Generate predictions on test set

# Print test results
print("Test Results:")
print(test_output.metrics)

Test Results:
{'test_loss': 0.05863962322473526, 'test_model_preparation_time': 0.0031, 'test_micro_f1': 0.9665841584158416, 'test_macro_f1': 0.9620314177540451, 'test_weighted_f1': 0.9663930727270951, 'test_micro_precision': 0.9923761118170267, 'test_micro_recall': 0.9420989143546441, 'test_subset_accuracy': 0.9305431878895815, 'test_runtime': 41.765, 'test_samples_per_second': 26.889, 'test_steps_per_second': 13.456}

## **Detailed Classification Report for Each Label**

In [ ]:
from sklearn.metrics import classification_report

pred_output = trainer.predict(test_tokenized)
logits = np.nan_to_num(pred_output.predictions, nan=0.0, posinf=20.0, neginf=-20.0)
labels = pred_output.label_ids.astype(int)

probs = 1.0 / (1.0 + np.exp(-logits))
preds = (probs >= THRESHOLD).astype(int)

for i, label_name in enumerate(LABEL_COLS):
    print(f"\n========== {label_name} ==========")
    print(classification_report(labels[:, i], preds[:, i], zero_division=0))

========== is_toxic ==========
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       498
           1       1.00      0.97      0.98       625

    accuracy                           0.98      1123
   macro avg       0.98      0.98      0.98      1123
weighted avg       0.98      0.98      0.98      1123


========== threat ==========
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       964
           1       1.00      0.92      0.96       159

    accuracy                           0.99      1123
   macro avg       0.99      0.96      0.98      1123
weighted avg       0.99      0.99      0.99      1123


========== bullying ==========
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       840
           1       0.99      0.93      0.96       283

    accuracy                           0.98      1123
   macro avg       0.99      0.97      0.97      1123
weighted avg       0.98      0.98      0.98      1123


========== sexual_harassment ==========
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       948
           1       1.00      0.93      0.96       175

    accuracy                           0.99      1123
   macro avg       0.99      0.97      0.98      1123
weighted avg       0.99      0.99      0.99      1123


========== hate_speech ==========
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       936
           1       1.00      0.97      0.98       187

    accuracy                           0.99      1123
   macro avg       1.00      0.98      0.99      1123
weighted avg       0.99      0.99      0.99      1123


========== other_toxicity ==========
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       894
           1       0.96      0.89      0.92       229

    accuracy                           0.97      1123
   macro avg       0.97      0.94      0.95      1123
weighted avg       0.97      0.97      0.97      1123

# Analyze Results and Create DataFrame

In this section, we convert model predictions into a structured DataFrame for easier analysis.

We:
- Generate predictions from the model
- Convert logits into probabilities, then into binary predictions
- Create a table containing:
  - Original text
  - True labels
  - Predicted labels

We also add:
- A column indicating if the prediction is completely correct (all_correct)
- A column counting the number of errors per sample (num_errors)

This helps us:
- Analyze model errors
- Identify difficult cases
- Prepare results for visualization or saving

In [ ]:
import numpy as np
import pandas as pd

# Get model predictions on test data
test_output = trainer.predict(test_tokenized)
# Clean invalid numerical values
logits = np.nan_to_num(test_output.predictions, nan=0.0, posinf=20.0, neginf=-20.0)
labels = test_output.label_ids.astype(int)

# Convert logits to probabilities
probs = 1.0 / (1.0 + np.exp(-logits))
# Convert probabilities to binary predictions
preds = (probs >= THRESHOLD).astype(int)

# conver to DataFrame
results_df = pd.DataFrame()

# texts
results_df["text"] = test_df[TEXT_COL].reset_index(drop=True)

# Add true labels
for i, col in enumerate(LABEL_COLS):
    results_df[f"true_{col}"] = labels[:, i]

# Add predicted labels
for i, col in enumerate(LABEL_COLS):
    results_df[f"pred_{col}"] = preds[:, i]

# Check if all labels are correctly predicted
results_df["all_correct"] = (labels == preds).all(axis=1)

# Count number of errors per sample
results_df["num_errors"] = (labels != preds).sum(axis=1)

results_df.head()

,text,true_is_toxic,true_threat,true_bullying,true_sexual_harassment,true_hate_speech,true_other_toxicity,pred_is_toxic,pred_threat,pred_bullying,pred_sexual_harassment,pred_hate_speech,pred_other_toxicity,all_correct,num_errors
0,"I really really want to like this game, and gi...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
1,The player culture in FiveM keeps overshadowin...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
2,Does your platformer have meat it in? Didn't t...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
3,"Honestly, Paladins gets ugly fast. The culture...",1,0,1,0,0,1,1,0,1,0,0,1,True,0
4,I remember when this came out and everyone was...,0,0,0,0,0,0,0,0,0,0,0,0,True,0

Display Full Results

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

results_df

,text,true_is_toxic,true_threat,true_bullying,true_sexual_harassment,true_hate_speech,true_other_toxicity,pred_is_toxic,pred_threat,pred_bullying,pred_sexual_harassment,pred_hate_speech,pred_other_toxicity,all_correct,num_errors
0,"I really really want to like this game, and gi...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
1,The player culture in FiveM keeps overshadowin...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
2,Does your platformer have meat it in? Didn't t...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
3,"Honestly, Paladins gets ugly fast. The culture...",1,0,1,0,0,1,1,0,1,0,0,1,True,0
4,I remember when this came out and everyone was...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
5,"At this point, EA FC gets ugly fast. The cultu...",1,1,1,0,1,0,1,0,1,0,1,0,False,1
6,"on the weekend, i do not think Marvel Rivals i...",1,0,0,0,1,1,1,0,0,0,1,1,True,0
7,this game always puts you in a team with dumbass,0,0,0,0,0,0,0,0,0,0,0,0,True,0
8,as much as this game is a piece of history for...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
9,The graphics migth be outdated but it's still ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
10,game is riddled with trolls i get matches wher...,1,0,1,0,0,1,0,0,0,0,0,1,False,2
11,Not that bad for what it is a mobile game. Mor...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
12,"even in casual, i can deal with losing in FIFA...",1,1,0,1,1,0,1,1,0,1,1,0,True,0
13,Pecking good game!,0,0,0,0,0,0,0,0,0,0,0,0,True,0
14,played only demo buggy as hell and unnerving c...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
15,Very fun and challenging game with cool pixel ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
16,super fun and it makes you want to keep playin...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
17,Decent game just have to follow the tutorials ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
18,My issue with Diablo IV has almost nothing to ...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
19,overcook for ever,0,0,0,0,0,0,0,0,0,0,0,0,True,0
20,The community around Apex ranked feels worse t...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
21,I've played enough Apex Legends to know the me...,1,0,0,1,0,0,1,0,0,1,0,0,True,0
22,Great party game to play with your friends. Ex...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
23,"do not f cking buy this, this is the worst gam...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
24,shitty meme game you know that feeling when a ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
25,"This review is of course, of my personal views...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
26,I love this game more than I would have though...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
27,This is a great game. If you like side scrolli...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
28,Great Game!! This is a hard game that is reall...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
29,"More often than not, New World gets ugly fast....",1,0,0,0,1,0,1,0,0,0,1,0,True,0
30,VRChat gets ugly socially pretty fast. The cul...,1,0,1,1,0,0,1,0,1,1,0,1,False,1
31,game plays itself and is pretty much a carbon ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
32,i can t play co op without the game fucking di...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
33,This is the game with the most instances of th...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
34,Not recommended. My biggest problem with it is...,1,1,1,0,1,0,1,1,1,0,0,0,False,1
35,Better than Rainbow Six,0,0,0,0,0,0,0,0,0,0,0,0,True,0
36,My issue with FIFA Ultimate Team has almost no...,1,0,1,0,1,0,1,0,1,0,1,0,True,0
37,"h1 Supermega briliant awesome story, and the b...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
38,fuck you gaben,0,0,0,0,0,0,0,0,0,0,0,0,True,0
39,This game has great gameplay and with a couple...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
40,Mortal Kombat 1 gets ugly socially pretty fast...,1,0,1,0,1,0,1,0,1,0,1,0,True,0
41,Ok Where do i start with this game that doesn'...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
42,I got this game in a Humble Bundle monthly cho...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
43,get like a winstreak then got matched absolute...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
44,World of Warcraft would be easier to recommend...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
45,My issue with Destiny 2 has almost nothing to ...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
46,it has a shitty plot line and extremely short ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
47,"Ark has a decent core loop, yet the player cul...",1,1,1,0,1,0,1,0,1,0,1,0,False,1
48,One of the best platforming games I've ever pl...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
49,I don't hate Black Desert Online; I hate what ...,1,0,0,0,1,0,1,0,0,0,1,0,True,0
50,"Not recommended. Straight up, I can enjoy New ...",1,1,0,0,0,0,1,1,0,0,0,0,True,0
51,Good game for killing Nazi scum,0,0,0,0,0,0,0,0,0,0,0,0,True,0
52,Not recommended. My issue with Fortnite isn't ...,1,0,0,1,1,0,1,0,0,1,1,0,True,0
53,Decent Game if you are a Metroidvania fan,0,0,0,0,0,0,0,0,0,0,0,0,True,0
54,Brawlhalla gets ugly socially pretty fast. The...,1,1,0,0,0,1,1,1,0,0,0,1,True,0
55,Mehh. Super cool. I like it. Although I find c...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
56,so as you might notice i am not at all an acti...,1,0,0,1,0,0,0,0,0,0,0,0,False,2
57,My issue with CS2 isn't that it's hard or swea...,1,0,1,0,0,1,1,0,1,0,0,1,True,0
58,truly a masterpiece,0,0,0,0,0,0,0,0,0,0,0,0,True,0
59,Its good i guess,0,0,0,0,0,0,0,0,0,0,0,0,True,0
60,Not recommended. What pushed me away from Ark ...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
61,Dead by Daylight would be easier to recommend ...,1,1,0,0,0,0,1,1,0,0,0,0,True,0
62,"Honestly, Overwatch ranked gets ugly fast. A l...",1,0,1,1,0,0,1,0,1,1,0,0,True,0
63,"In this game, it is possible to achieve a dog ...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
64,I truly love this game. One of my all-time fav...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
65,"Very good game, tight-fluid gameplay, good gam...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
66,What keeps getting overlooked in Fortnite is t...,1,1,1,0,0,0,1,1,1,0,0,0,True,0
67,best metroidvainia? idk maybe,0,0,0,0,0,0,0,0,0,0,0,0,True,0
68,Among Us gets ugly socially pretty fast. In th...,1,1,0,0,0,1,1,1,0,0,0,1,True,0
69,"Whenever I come back to Dead by Daylight, I re...",1,0,1,1,0,0,1,0,1,1,0,0,True,0
70,"Honestly, Brawlhalla gets ugly fast. What both...",1,1,1,0,0,0,1,1,1,0,0,0,True,0
71,"Even when Roblox is playable, the social atmos...",1,0,1,0,1,0,1,0,1,0,1,0,True,0
72,"The matches in Warframe can be great, then the...",1,0,1,0,0,1,1,0,1,0,0,1,True,0
73,"If I'm being honest, Siege X gets ugly fast. W...",1,1,0,0,0,0,1,1,0,0,0,0,True,0
74,The problem with R6 ranked is mostly the peopl...,1,1,1,0,1,0,1,0,1,0,1,0,False,1
75,"A fun automation game, that can suck you in an...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
76,My issue with Sea of Thieves has almost nothin...,1,0,0,0,1,0,1,0,0,0,1,0,True,0
77,Expected something good without having seen an...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
78,I learned a lot about myself and my personal l...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
79,"Extremely Difficult, but very fun tactical sho...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
80,The problem with Siege X is mostly the people....,1,1,0,0,1,0,1,1,0,0,1,0,True,0
81,Good point and click game with every single pu...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
82,"I still like parts of R6 ranked, but the playe...",1,0,0,0,0,1,1,0,0,0,0,1,True,0
83,fucking bitch,0,0,0,0,0,0,0,0,0,0,0,0,True,0
84,Guild Wars 2 is fine until the players start a...,1,0,0,0,1,0,1,0,0,0,1,0,True,0
85,I can handle losing in Marvel Rivals; what I c...,1,0,1,0,0,1,1,0,1,0,0,1,True,0
86,I've had enough time with Overwatch ranked to ...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
87,I am a massive resident evil fan have liked ev...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
88,dont play this if you dont want to kill yourse...,1,0,0,0,1,0,1,0,0,0,0,0,False,1
89,i really like this game but there are so many ...,1,1,1,0,0,1,1,0,1,0,0,1,False,1
90,Fortnite can be genuinely fun until the social...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
91,"lately, i do not think Warframe is ruined by b...",1,0,0,1,1,0,1,0,0,1,1,0,True,0
92,"Honestly, New World gets ugly fast. The cultur...",1,1,1,0,0,0,1,1,1,0,0,0,True,0
93,Played about 10 hours on this so far and it is...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
94,Guild Wars 2 isn't even the problem half the t...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
95,"New World has a decent core loop, yet the play...",1,0,1,0,0,0,1,0,1,0,0,0,True,0
96,Tekken 8 gets ugly socially pretty fast. A lot...,1,0,0,1,1,0,1,0,0,1,1,0,True,0
97,"if you like Deus Ex get it, you'll have your f...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
98,visuals and dog fights are very fun. ui can be...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
99,fcking game cant find play when you got low pr...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
100,Whenever people ask why I stopped playing Apex...,1,0,0,0,1,0,1,0,0,0,1,0,True,0
101,Black Desert Online would be a lot more fun if...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
102,"Escape from Tarkov: I can deal with losing, bu...",1,0,1,1,0,0,1,0,1,1,0,0,True,0
103,"I keep coming back and every time, Arena Break...",1,0,1,1,0,0,1,0,1,1,0,0,True,0
104,I'm so tired and I'm very happy I've made it. ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
105,i was on the fence before writing out this rev...,1,0,0,0,0,1,0,0,0,0,0,0,False,2
106,The finest metroidvania I have ever played. Th...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
107,"If I'm being honest, DayZ gets ugly fast. The ...",1,0,0,0,1,0,1,0,0,0,1,0,True,0
108,"most nights, when i think about why Valorant f...",1,0,0,0,1,0,1,0,0,0,1,0,True,0
109,The last game Firaxis made before the dry rot ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
110,"For me, Valorant comp gets ugly fast. What bot...",1,1,0,0,0,1,1,1,0,0,0,1,True,0
111,"A great game anytime, anywhere.",0,0,0,0,0,0,0,0,0,0,0,0,True,0
112,Rust: One bad round and the lobby decides some...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
113,"I still like parts of League of Legends, but t...",1,0,0,0,1,0,1,0,0,0,1,0,True,0
114,About time people paid for this game!,0,0,0,0,0,0,0,0,0,0,0,0,True,0
115,"The matches in Lost Ark can be great, then the...",1,1,1,0,0,0,1,1,1,0,0,0,True,0
116,"If I'm being honest, VRChat gets ugly fast. A ...",1,0,1,0,1,0,1,0,1,0,1,0,True,0
117,"in my experience, personally Mortal Kombat, th...",1,0,0,1,1,0,1,0,0,1,1,0,True,0
118,Celeste is simply put a really great platforme...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
119,"Great game so far, but needs work, i can see w...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
120,Teamfight Tactics isn't even the problem half ...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
121,"More often than not, Dota 2 gets ugly fast. Th...",1,1,0,0,0,0,1,1,0,0,0,0,True,0
122,i like this as the character creator is good,0,0,0,0,0,0,0,0,0,0,0,0,True,0
123,"Not even exaggerating, Folks throw games on pu...",1,0,0,0,0,1,1,0,0,0,0,1,True,0
124,left dead is pretty much unplayable the way it...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
125,really fun game to play with friends,0,0,0,0,0,0,0,0,0,0,0,0,True,0
126,Lost Ark is fine until the players start actin...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
127,the main reason i dropped Apex Legends is that...,1,0,1,0,0,1,1,0,1,0,0,1,True,0
128,The player culture in Diablo IV keeps overshad...,1,1,0,0,0,0,1,1,0,0,0,0,True,0
129,"most nights, i can deal with losing in Valoran...",1,1,0,1,1,1,1,1,0,1,1,1,True,0
130,the worst part of Mortal Kombat is that too ma...,1,0,0,1,1,0,1,0,0,1,1,0,True,0
131,do not get me wrong the game is timeless and g...,1,0,0,0,0,0,0,0,0,0,0,0,False,1
132,What keeps souring Fortnite for me is that one...,1,0,1,0,1,0,1,0,1,0,1,0,True,0
133,"I like the game, hate the room: If you miss on...",1,0,1,0,0,1,1,0,1,0,0,1,True,0
134,it was ok,0,0,0,0,0,0,0,0,0,0,0,0,True,0
135,this game is fun but the servers are filled wi...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
136,"in my experience, the worst part of Apex Legen...",1,0,1,1,0,1,1,0,1,1,0,1,True,0
137,Now I'm not sure what all these negative revie...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
138,"More often than not, Overwatch 2 gets ugly fas...",1,0,1,0,0,1,1,0,1,0,0,1,True,0
139,fucking anti cheat vac fuck you never lets me ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
140,"The matches in GTA Online can be great, then t...",1,1,0,0,0,0,1,1,0,0,0,0,True,0
141,I've played enough Roblox to know the mechanic...,1,0,1,1,0,0,1,0,1,1,0,0,True,0
142,I don't hate League of Legends; I hate what th...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
143,"I wanted to like it but, I keep giving Left 4 ...",1,0,0,0,1,1,1,0,0,0,1,1,True,0
144,The Finals would be easier to recommend if peo...,1,1,1,1,0,0,1,1,1,0,0,0,False,1
145,the bot and cheaters problem has gotten out of...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
146,The part people downplay with EA FC is how bad...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
147,A solid spin-off of Human Revolution. It is re...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
148,My issue with Fortnite has almost nothing to d...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
149,Really butters my muffin,0,0,0,0,0,0,0,0,0,0,0,0,True,0
150,"Fantastic game. I love the story, all the cool...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
151,valve why the hell you move chinesee fucking d...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
152,The rough part of Halo Infinite isn't the grin...,1,1,0,0,0,0,1,1,0,0,0,0,True,0
153,Would smash Mansa Musa,0,0,0,0,0,0,0,0,0,0,0,0,True,0
154,its hard af,0,0,0,0,0,0,0,0,0,0,0,0,True,0
155,A few matches of Minecraft are usually enough ...,1,0,0,1,0,0,1,0,0,1,0,0,True,0
156,Rogue-likes these days have high standards. En...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
157,"Fun, complex and addicting. If you're new to t...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
158,Sea of Thieves gets ugly socially pretty fast....,1,0,0,1,1,0,1,0,0,1,1,0,True,0
159,My issue with ARK has almost nothing to do wit...,1,1,0,0,0,0,1,1,0,0,0,0,True,0
160,[Community rant] What pushed me away from Rust...,1,0,1,1,1,0,1,0,1,0,1,0,False,1
161,"One of the best FPS games ever, completed it m...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
162,Buy this franchise..No further words needed.,0,0,0,0,0,0,0,0,0,0,0,0,True,0
163,beat dark souls 3 on new game plus and i still...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
164,Cave Story is a jumping-and-shooting action ga...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
165,"from what i have seen, if someone asked me why...",1,1,0,1,0,0,1,1,0,1,0,0,True,0
166,Step 1 install rimworld Step 2 install mods st...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
167,The ongoing problem with FIFA Ultimate Team is...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
168,Path of Exile would be easier to recommend if ...,1,0,0,0,1,0,1,0,0,0,1,0,True,0
169,"What killed it for me was, PUBG is not what we...",1,0,1,0,1,0,1,0,1,0,1,0,True,0
170,when i was i got told to kill myself by a year...,1,1,0,0,0,1,0,0,0,0,0,0,False,3
171,Most of my bad memories with CS2 premier come ...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
172,I don't understand why I bought this game. It'...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
173,It's fun if you are playing a custom server an...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
174,What pushed me away from Escape from Tarkov wa...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
175,"Rust: The reason I stopped playing is, Rust is...",1,0,0,1,0,1,1,0,0,1,0,1,True,0
176,"Not that far into the game as yet, but as surv...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
177,It is an amusing take on Battleroyale that isn...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
178,I love the game! It makes believe that I'm act...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
179,"from what i have seen, i can deal with losing ...",1,0,0,1,1,1,1,0,0,1,1,1,True,0
180,You can see both the touch of Machine Games an...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
181,ridden with bots more than france was with bed...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
182,The social side of Dota 2 has gotten exhaustin...,1,0,0,1,0,0,1,0,0,1,0,0,True,0
183,One of my killing time game.. Excelent! 9 10,0,0,0,0,0,0,0,0,0,0,0,0,True,0
184,"most nights, when i think about why Call of Du...",1,1,1,0,1,1,1,1,1,0,1,1,True,0
185,this game is horrible broken and incomplete to...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
186,Love this game.. I played the snot out of the ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
187,fix your stupid game valve good lord,0,0,0,0,0,0,0,0,0,0,0,0,True,0
188,I bought the five anniversary package on steam...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
189,"especially in ranked, i do not think Path of E...",1,0,1,1,0,0,1,0,1,1,0,0,True,0
190,Great game. A lot of fun alone but best with s...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
191,Shit slaps hard,0,0,0,0,0,0,0,0,0,0,0,0,True,0
192,"If I'm being honest, League solo queue gets ug...",1,0,0,0,0,1,1,0,0,0,0,1,True,0
193,please fix you fucking anti cheat idiot,0,0,0,0,0,0,0,0,0,0,0,0,True,0
194,if you aren't playing this game you aren't a g...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
195,"especially in ranked, i can deal with losing i...",1,1,0,1,1,0,1,1,0,1,1,0,True,0
196,I've played enough Sea of Thieves to know the ...,1,1,1,0,0,0,1,1,1,0,0,0,True,0
197,Rainbow Six Siege would be enjoyable if the co...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
198,"A really nice game, a shame not allot of peopl...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
199,"At this point, Brawlhalla gets ugly fast. Matc...",1,0,0,0,0,1,1,0,0,0,0,1,True,0
200,My issue with Halo Infinite has almost nothing...,1,0,1,1,0,0,1,0,1,1,0,0,True,0
201,Smite 2 can be genuinely fun until the social ...,1,0,1,0,0,0,1,0,1,0,0,0,True,0
202,"lately, i keep coming back to Dota 2 because t...",1,1,0,0,0,0,1,1,0,0,0,0,True,0
203,get your luck with the random matchmaking shit...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
204,"I expected sweat, not, Final Fantasy XIV is no...",1,0,1,1,1,0,1,0,1,0,1,0,False,1
205,A few matches of World of Warcraft are usually...,1,0,0,1,0,0,1,0,0,1,0,0,True,0
206,kinda scary but not too bad.,0,0,0,0,0,0,0,0,0,0,0,0,True,0
207,this is a game ive come to enjoy for the past ...,1,0,1,0,0,0,0,0,0,0,0,0,False,2
208,FiveM gets ugly socially pretty fast. A lot of...,1,0,1,0,0,1,1,0,1,0,0,1,True,0
209,Amazing Graphics and very interesting and deta...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
210,love the game but after playing it for so long...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
211,What keeps getting overlooked in Valorant comp...,1,0,1,1,0,0,1,0,1,1,0,0,True,0
212,"Whenever people ask why I cooled on Destiny 2,...",1,0,1,0,0,0,1,0,1,0,0,0,True,0
213,"Honestly, Diablo IV gets ugly fast. Match chat...",1,0,0,0,0,1,1,0,0,0,0,1,True,0
214,Great Metroidvania. Even though the graphics a...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
215,World of Warcraft would be easier to recommend...,1,1,1,0,1,0,1,0,1,0,1,0,False,1
216,got shot running up stairs body glitched and w...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
217,flat human go bye bye,0,0,0,0,0,0,0,0,0,0,0,0,True,0
218,"More often than not, Fortnite gets ugly fast. ...",1,0,0,1,1,0,1,0,0,1,1,0,True,0
219,I do think that this game has much potential t...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
220,The community around osu! feels worse than the...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
221,yes yes i sold my kidney to buy this game D th...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
222,Awesome game with room for innovation and enjo...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
223,"Good stuff, well designed, good stuff. Folks a...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
224,this game is very good,0,0,0,0,0,0,0,0,0,0,0,0,True,0
225,"Overall, this game feels quite nice to play. T...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
226,Naraka: Bladepoint is fine until the players s...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
227,My biggest issue with Black Desert Online rema...,1,0,0,0,0,1,1,0,0,0,0,1,True,0
228,The Binding of Isaac Rebirth is an amazing rec...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
229,What keeps getting overlooked in Dead by Dayli...,1,0,0,0,1,0,1,0,0,0,1,0,True,0
230,Rocket League is exhausting because some playe...,1,1,0,1,1,1,1,0,0,1,1,1,False,1
231,great game have enjoyed it n console now on pc...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
232,"If you're into games like SMB, this is a must....",0,0,0,0,0,0,0,0,0,0,0,0,True,0
233,support your fucking game valve,0,0,0,0,0,0,0,0,0,0,0,0,True,0
234,"It was a broken mess in EA, but now it is so m...",0,0,0,0,0,0,0,0,0,0,0,0,True,0
235,shitty and uninspiring steals your friends awa...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
236,I've played enough Call of Duty to know the me...,1,0,1,0,0,1,1,0,1,0,0,1,True,0
237,bots are gay and if you don t fix them that s ...,0,0,0,0,0,0,0,0,0,0,0,0,True,0
238,What keeps getting overlooked in Halo Infinite...,1,1,1,0,0,0,1,1,1,0,0,0,True,0

**Save Results to File**

In [ ]:
file_name = "test_results_full.csv"
results_df.to_csv(file_name, index=False)

print(f"Saved as {file_name}")

Saved as test_results_full.csv

**Analyze Data Distribution**

In [ ]:
import pandas as pd

df = pd.read_excel("final_data_for_processing.xlsx")

toxic_count = (df["is_toxic"] == 1).sum()
print("عدد التوكسيك:", toxic_count)
toxic_count = (df["is_toxic"] == 0).sum()
print("عدد  التوكسيك:", toxic_count)

عدد التوكسيك: 5987
عدد  التوكسيك: 5235

## Manual Test on Custom Sentences

This section performs a manual test using custom-written sentences instead of the original test dataset.

In [ ]:
# =========================
# MANUAL TEST
# =========================

import torch
import numpy as np

texts = [
    "Every match in this game turns into people insulting the weakest player until they leave.",
    "I stopped using voice chat because some players kept threatening to find me and hurt me.",
    "The community is awful, they keep mocking new players for every small mistake.",
    "Some random guy in the lobby kept making disgusting sexual comments at me the whole game.",
    "I have seen players use racist slurs in chat whenever they get angry.",
    "The matchmaking is bad and the servers lag all the time.",
    "People in ranked keep telling others to uninstall and saying they are useless.",
    "One player said he would track me down if I queued against him again.",
    "The fanbase gets really defensive, but I would not call it toxic all the time.",
    "Women get harassed so much in this game's voice chat that many of them avoid speaking."
]

# Expected true labels for each sentence
true_labels = [
    [1,0,1,0,0,0],  # insulting weakest player
    [1,1,0,0,0,0],  # direct threat
    [1,0,1,0,0,0],  # mocking new players
    [1,0,0,1,0,0],  # sexual harassment
    [1,0,0,0,1,0],  # hate speech
    [0,0,0,0,0,0],  # technical complaint only
    [1,0,1,0,0,0],  # bullying
    [1,1,0,0,0,0],  # threat
    [0,0,0,0,0,0],  # opinion, not clearly toxicity
    [1,0,0,1,0,0]   # harassment toward women + hate element
]


# Use the trained model
model = trainer.model
model.eval()

# Get the model device
device = model.device

inputs = tokenizer(
    texts,
    padding=True,
    truncation=True,
    return_tensors="pt"
)

# Move inputs to the same device as the model
inputs = {k: v.to(device) for k, v in inputs.items()}

with torch.no_grad():
    outputs = model(**inputs)
    logits = outputs.logits

# Convert logits to probabilities using Sigmoid
probs = torch.sigmoid(logits).cpu().numpy()
preds = (probs >= THRESHOLD).astype(int)

correct = 0

# Display results for each sentence
for i in range(len(texts)):
    print("\n====================")
    print("TEXT:", texts[i])
    print("TRUE:", true_labels[i])
    print("PRED:", preds[i].tolist())
    print("SCORES:", [round(x, 3) for x in probs[i].tolist()])

    # Check whether all labels are predicted correctly
    if (preds[i] == true_labels[i]).all():
        print("✅ CORRECT")
        correct += 1
    else:
        print("❌ WRONG")

print("\n====================")
print(f"Correct: {correct}/{len(texts)}")
print(f"Accuracy: {correct/len(texts):.2f}")

====================
TEXT: Every match in this game turns into people insulting the weakest player until they leave.
TRUE: [1, 0, 1, 0, 0, 0]
PRED: [1, 0, 1, 0, 0, 0]
SCORES: [0.999, 0.0, 1.0, 0.0, 0.001, 0.036]
✅ CORRECT

====================
TEXT: I stopped using voice chat because some players kept threatening to find me and hurt me.
TRUE: [1, 1, 0, 0, 0, 0]
PRED: [1, 1, 0, 0, 0, 0]
SCORES: [0.999, 1.0, 0.028, 0.001, 0.003, 0.146]
✅ CORRECT

====================
TEXT: The community is awful, they keep mocking new players for every small mistake.
TRUE: [1, 0, 1, 0, 0, 0]
PRED: [1, 0, 1, 0, 0, 0]
SCORES: [1.0, 0.002, 1.0, 0.002, 0.001, 0.03]
✅ CORRECT

====================
TEXT: Some random guy in the lobby kept making disgusting sexual comments at me the whole game.
TRUE: [1, 0, 0, 1, 0, 0]
PRED: [1, 0, 0, 1, 0, 0]
SCORES: [0.973, 0.019, 0.002, 0.997, 0.001, 0.033]
✅ CORRECT

====================
TEXT: I have seen players use racist slurs in chat whenever they get angry.
TRUE: [1, 0, 0, 0, 1, 0]
PRED: [1, 0, 0, 0, 1, 0]
SCORES: [1.0, 0.038, 0.001, 0.003, 1.0, 0.132]
✅ CORRECT

====================
TEXT: The matchmaking is bad and the servers lag all the time.
TRUE: [0, 0, 0, 0, 0, 0]
PRED: [0, 0, 0, 0, 0, 0]
SCORES: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
✅ CORRECT

====================
TEXT: People in ranked keep telling others to uninstall and saying they are useless.
TRUE: [1, 0, 1, 0, 0, 0]
PRED: [1, 0, 1, 0, 0, 0]
SCORES: [0.998, 0.091, 1.0, 0.014, 0.028, 0.218]
✅ CORRECT

====================
TEXT: One player said he would track me down if I queued against him again.
TRUE: [1, 1, 0, 0, 0, 0]
PRED: [1, 1, 0, 0, 0, 0]
SCORES: [0.53, 0.995, 0.004, 0.001, 0.0, 0.029]
✅ CORRECT

====================
TEXT: The fanbase gets really defensive, but I would not call it toxic all the time.
TRUE: [0, 0, 0, 0, 0, 0]
PRED: [1, 0, 0, 0, 0, 0]
SCORES: [0.957, 0.0, 0.0, 0.0, 0.0, 0.058]
❌ WRONG

====================
TEXT: Women get harassed so much in this game's voice chat that many of them avoid speaking.
TRUE: [1, 0, 0, 1, 0, 0]
PRED: [1, 0, 0, 1, 0, 0]
SCORES: [0.999, 0.0, 0.0, 1.0, 0.001, 0.002]
✅ CORRECT

====================
Correct: 9/10
Accuracy: 0.90

The model achieved strong performance in the manual test, correctly classifying 9 out of 10 sentences with an accuracy of 90%. This indicates its high capability in detecting explicit toxicity patterns such as threats, bullying, and hate speech with high confidence. The model also demonstrated good distinction between toxic and non-toxic content, as it correctly handled neutral technical complaints. However, a minor limitation appeared in understanding more complex linguistic context, particularly in sentences involving negation, where it misclassified one sentence as toxic despite it expressing the opposite. Overall, the model shows excellent performance in clear cases, with slight room for improvement in handling nuanced and context-dependent language.